// Fictional people for exploring Discover when no live source is connected. NOT real people and
// NOT search results from any website. No contact details are included on purpose: Talyn never
// invents them, even for samples. Some fields are deliberately missing to show "not established".

type Exp = { title: string; company: string; start: string; end: string | null; description: string };
export type SampleProfile = {
  id: string;
  name: string;
  title: string | null;
  company: string | null;
  location: string | null;
  skills: string[];
  summary: string;
  experience: Exp[];
  monthsSinceUpdate: number | null; // null = source gives no date
};

export const SAMPLE_PROFILES: SampleProfile[] = [
  {
    id: "sample-01",
    name: "Avery Lindqvist",
    title: "Senior Backend Engineer",
    company: "Kestrel Systems (fictional)",
    location: "Berlin, Germany",
    skills: ["Go", "PostgreSQL", "Kubernetes", "gRPC", "AWS"],
    summary: "Builds payment and ledger services. Led a PostgreSQL partitioning project for a high-volume transactions table.",
    experience: [
      { title: "Senior Backend Engineer", company: "Kestrel Systems (fictional)", start: "2021-04", end: null, description: "Owns the ledger service in Go; on-call lead; PostgreSQL performance work." },
      { title: "Software Engineer", company: "Brightline Labs (fictional)", start: "2017-09", end: "2021-03", description: "Python and Django APIs; migrated services to Kubernetes." },
    ],
    monthsSinceUpdate: 2,
  },
  {
    id: "sample-02",
    name: "Mateo Ferreira",
    title: "Backend Developer",
    company: "Harbor & Finch (fictional)",
    location: "Lisbon, Portugal",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Kafka"],
    summary: "Event-driven systems with Kafka. Interested in observability tooling.",
    experience: [{ title: "Backend Developer", company: "Harbor & Finch (fictional)", start: "2020-01", end: null, description: "Java/Spring services, Kafka consumers, PostgreSQL schema design." }],
    monthsSinceUpdate: 5,
  },
  {
    id: "sample-03",
    name: "Priya Raman",
    title: "Staff Software Engineer",
    company: "Larkspur Health (fictional)",
    location: null,
    skills: ["TypeScript", "Node.js", "React", "PostgreSQL", "System design"],
    summary: "Full-stack engineer who has led platform teams of 6–8 engineers.",
    experience: [{ title: "Staff Software Engineer", company: "Larkspur Health (fictional)", start: "2019-06", end: null, description: "Technical lead for the scheduling platform (Node.js, React, PostgreSQL)." }],
    monthsSinceUpdate: null,
  },
  {
    id: "sample-04",
    name: "Jonah Okafor",
    title: "Site Reliability Engineer",
    company: "Pinecrest Cloud (fictional)",
    location: "Remote — EU",
    skills: ["Kubernetes", "Terraform", "AWS", "Prometheus", "Go"],
    summary: "Runs multi-region Kubernetes clusters; incident management and SLOs.",
    experience: [{ title: "Site Reliability Engineer", company: "Pinecrest Cloud (fictional)", start: "2018-02", end: null, description: "Terraform, AWS, Prometheus alerting, incident reviews." }],
    monthsSinceUpdate: 26,
  },
  {
    id: "sample-05",
    name: "Sofia Marchetti",
    title: "Data Engineer",
    company: "Northvale Analytics (fictional)",
    location: "Milan, Italy",
    skills: ["Python", "SQL", "Airflow", "dbt", "Snowflake"],
    summary: "Builds batch and streaming pipelines; data modeling with dbt.",
    experience: [{ title: "Data Engineer", company: "Northvale Analytics (fictional)", start: "2020-10", end: null, description: "Airflow orchestration, dbt models, Snowflake cost optimisation." }],
    monthsSinceUpdate: 3,
  },
  {
    id: "sample-06",
    name: "Hana Kobayashi",
    title: "Senior Data Scientist",
    company: "Tidewater Retail (fictional)",
    location: "London, United Kingdom",
    skills: ["Python", "Machine learning", "Experimentation", "SQL", "Forecasting"],
    summary: "Demand forecasting and A/B testing for e-commerce.",
    experience: [{ title: "Senior Data Scientist", company: "Tidewater Retail (fictional)", start: "2019-03", end: null, description: "Forecasting models in Python; experimentation platform owner." }],
    monthsSinceUpdate: 7,
  },
  {
    id: "sample-07",
    name: "Daniel Abebe",
    title: "Product Designer",
    company: "Quill & Co (fictional)",
    location: "Amsterdam, Netherlands",
    skills: ["Figma", "User research", "Design systems", "Prototyping"],
    summary: "Designs B2B workflow tools; maintains a component library.",
    experience: [{ title: "Product Designer", company: "Quill & Co (fictional)", start: "2021-01", end: null, description: "End-to-end design for workflow features; design system in Figma." }],
    monthsSinceUpdate: 1,
  },
  {
    id: "sample-08",
    name: "Lucía Herrera",
    title: "Senior Product Manager",
    company: "Brightline Labs (fictional)",
    location: "Madrid, Spain",
    skills: ["Product strategy", "Roadmapping", "B2B SaaS", "Analytics"],
    summary: "Owns onboarding and activation for a B2B SaaS product.",
    experience: [{ title: "Senior Product Manager", company: "Brightline Labs (fictional)", start: "2020-05", end: null, description: "Roadmap for onboarding; worked with design and data on activation metrics." }],
    monthsSinceUpdate: 4,
  },
  {
    id: "sample-09",
    name: "Tomasz Nowak",
    title: "Frontend Engineer",
    company: "Kestrel Systems (fictional)",
    location: "Warsaw, Poland",
    skills: ["TypeScript", "React", "Next.js", "Accessibility", "CSS"],
    summary: "Accessible, fast web UIs; contributed to a shared React component library.",
    experience: [{ title: "Frontend Engineer", company: "Kestrel Systems (fictional)", start: "2021-08", end: null, description: "React and Next.js; WCAG audits and fixes." }],
    monthsSinceUpdate: 6,
  },
  {
    id: "sample-10",
    name: "Grace Mensah",
    title: "Technical Recruiter",
    company: "Larkspur Health (fictional)",
    location: "Manchester, United Kingdom",
    skills: ["Technical recruiting", "Sourcing", "Stakeholder management", "ATS administration"],
    summary: "Hires engineering and data roles; runs structured interview training.",
    experience: [{ title: "Technical Recruiter", company: "Larkspur Health (fictional)", start: "2019-11", end: null, description: "Full-cycle recruiting for engineering; structured interviews." }],
    monthsSinceUpdate: 8,
  },
  {
    id: "sample-11",
    name: "Oliver Brandt",
    title: "Account Executive",
    company: "Harbor & Finch (fictional)",
    location: "Hamburg, Germany",
    skills: ["B2B sales", "SaaS", "Salesforce", "Negotiation"],
    summary: "Mid-market SaaS sales; consistently managed a full pipeline.",
    experience: [{ title: "Account Executive", company: "Harbor & Finch (fictional)", start: "2020-02", end: null, description: "Mid-market new business; Salesforce pipeline management." }],
    monthsSinceUpdate: 2,
  },
  {
    id: "sample-12",
    name: "Amara Nwosu",
    title: "Customer Success Manager",
    company: "Pinecrest Cloud (fictional)",
    location: "Dublin, Ireland",
    skills: ["Customer success", "Onboarding", "Renewals", "SaaS"],
    summary: "Manages a book of enterprise accounts; onboarding programs.",
    experience: [{ title: "Customer Success Manager", company: "Pinecrest Cloud (fictional)", start: "2021-03", end: null, description: "Enterprise onboarding and renewals." }],
    monthsSinceUpdate: 10,
  },
  {
    id: "sample-13",
    name: "Ravi Shankar",
    title: "Financial Analyst",
    company: "Northvale Analytics (fictional)",
    location: "Bengaluru, India",
    skills: ["Financial modeling", "Excel", "FP&A", "SQL"],
    summary: "Budgeting and forecasting; built the monthly reporting pack.",
    experience: [{ title: "Financial Analyst", company: "Northvale Analytics (fictional)", start: "2020-07", end: null, description: "FP&A, financial models, monthly reporting." }],
    monthsSinceUpdate: 3,
  },
  {
    id: "sample-14",
    name: "Elena Popescu",
    title: "QA Engineer",
    company: "Quill & Co (fictional)",
    location: "Bucharest, Romania",
    skills: ["Test automation", "Playwright", "TypeScript", "CI"],
    summary: "End-to-end test automation and CI pipelines.",
    experience: [{ title: "QA Engineer", company: "Quill & Co (fictional)", start: "2019-09", end: null, description: "Playwright suites, CI integration, release testing." }],
    monthsSinceUpdate: 30,
  },
  {
    id: "sample-15",
    name: "Kai Tanaka",
    title: null,
    company: null,
    location: "Remote",
    skills: ["Python", "PostgreSQL", "APIs"],
    summary: "Freelance developer. Limited profile information available from this source.",
    experience: [],
    monthsSinceUpdate: null,
  },
  {
    id: "sample-16",
    name: "Nadia Haddad",
    title: "People Operations Partner",
    company: "Tidewater Retail (fictional)",
    location: "Paris, France",
    skills: ["HR operations", "Employee relations", "HRIS", "Onboarding"],
    summary: "HR business partner for operations teams.",
    experience: [{ title: "People Operations Partner", company: "Tidewater Retail (fictional)", start: "2018-05", end: null, description: "Employee relations, onboarding, HRIS administration." }],
    monthsSinceUpdate: 5,
  },
];
