import Link from "next/link";
import { Card, EmptyState, PageHeader, SectionTitle } from "@/components/ui";
import { aiStatus } from "@/lib/ai";
import { requireAuth } from "@/lib/auth";
import { db } from "@/lib/db";
import { ownRole } from "@/server/scope";
import { GenerateIcpButton, IcpApprovedView, IcpDraftEditor, type IcpView } from "./icp-editor";

export const metadata = { title: "Sourcing" };
// ICP generation and searches run as server actions on this page.
export const maxDuration = 300;

type IcpWithItems = Awaited<ReturnType<typeof loadIcps>>[number];
async function loadIcps(orgId: string, roleId: string) {
  return db.icp.findMany({ where: { orgId, roleId, status: { in: ["draft", "approved"] } }, include: { items: { orderBy: { position: "asc" } } }, orderBy: { version: "desc" } });
}
function toView(i: IcpWithItems): IcpView {
  return {
    id: i.id,
    version: i.version,
    status: i.status,
    generator: i.generator,
    criteriaVersion: i.criteriaVersion,
    approvedByName: i.approvedByName,
    approvedAt: i.approvedAt?.toISOString() ?? null,
    clarifications: JSON.parse(i.clarificationsJson),
    items: i.items,
  };
}

export default async function SourcingPage({ params }: { params: Promise<{ id: string }> }) {
  const auth = await requireAuth();
  const { id } = await params;
  const role = await ownRole(auth, id);
  const [approvedCriteria, icps] = await Promise.all([db.criterion.count({ where: { roleId: id, orgId: auth.orgId, status: "approved" } }), loadIcps(auth.orgId, id)]);
  const draft = icps.find((i) => i.status === "draft");
  const approved = icps.find((i) => i.status === "approved");
  const ai = aiStatus();

  return (
    <>
      <PageHeader
        eyebrow={
          <>
            <Link href="/roles" className="hover:text-ink">Roles</Link> / <Link href={`/roles/${role.id}`} className="hover:text-ink">{role.title}</Link>
          </>
        }
        title="Sourcing"
        meta={<span>Approved criteria → Ideal Candidate Profile → search strategy → authorized sources → your review</span>}
      />

      <section className="mb-8" aria-labelledby="icp-h">
        <SectionTitle
          hint="Who to look for. Built from the approved criteria and JD; you review every item. Only an approved profile drives search."
          action={
            approvedCriteria > 0 && !draft ? <GenerateIcpButton roleId={role.id} aiConfigured={ai.configured} label={approved ? "Generate a new version" : "Generate profile"} /> : null
          }
        >
          <span id="icp-h">Ideal Candidate Profile</span>
        </SectionTitle>
        {approvedCriteria === 0 ? (
          <EmptyState title="Approve criteria first" body="The profile is built from the role's approved criteria." action={<Link href={`/roles/${role.id}?tab=criteria`} className="font-medium underline">Go to criteria</Link>} />
        ) : draft ? (
          <>
            <div className="mb-3 flex items-center gap-3 text-[12.5px] text-muted">
              <span>
                Draft v{draft.version} · {draft.generator.startsWith("ai:") ? `generated by AI (${draft.generator.split(":")[2]?.split("/")[0]})` : draft.generator.startsWith("revision") ? `revision of v${draft.generator.split("-v").pop()}` : "built from approved criteria (not AI)"}
              </span>
              <span className="ml-auto">
                <GenerateIcpButton roleId={role.id} aiConfigured={ai.configured} label="Regenerate draft" />
              </span>
            </div>
            <IcpDraftEditor icp={toView(draft)} roleCriteriaVersion={role.criteriaVersion} />
          </>
        ) : approved ? (
          <Card className="p-5">
            <IcpApprovedView icp={toView(approved)} roleCriteriaVersion={role.criteriaVersion} />
          </Card>
        ) : (
          <EmptyState title="No profile yet" body="Generate a draft from the approved criteria. You'll review and approve it before any search." />
        )}
      </section>
    </>
  );
}
